apiVersion: apps/v1
kind: Deployment
metadata:
  name: swoom-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swoom-app 
  template:
    metadata:
      labels:
        app: swoom-app 
    spec:
      containers:
      - name: swoom-app 
        image: rowlandr71/swoom-app
        ports:
        - containerPort: 80
