apiVersion: apps/v1
kind: Deployment
metadata:
  name: swoom-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swoom-app 
  template:
    metadata:
      labels:
        app: swoom-app 
    spec:
      containers:
      - name: swoom-app 
        image: rowlandr71/swoom-app
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
